---
title: "r-vectors.qmd"
author: "Joshua Paul Cohen"
format: html
---

## lets create vectors or something idk help

```{r}
# vectors must contain elements of the same data type ----
marmots <- c("blue", "green", 4, "yellow")

# return it ----
marmots

# check class ----
# should be "character"
class(marmots)
```
```{r}
# pika pika thunderbolt
pika <- c(12.4, 6.8, 2.9, 8.8, 5)
pika
#class is "numeric"
class(pika)
```
these are all integer elements
```{r}
bear <- c(20L, 3L, 5L, 18L, 23L)

bear
#class is "integer"
#needs L for some reason???
class(bear)
```
## vector math

```{r}
# create vectors ----
ringtail <- c(4.3, 8.9, 2.6, 7.1)
fox <- c(9.0, 12.5, 5.4, 10.9)

# add ----
ringtail + fox

# if vectors are different sizes
# should yield error

ringtail2 <- c(4.3, 8.9, 2.6, 7.1)
fox2 <- c(9.0, 12.5, 5.4)
ringtail2 + fox2

#if have NA in a vector
#added vector will have NA
ringtail3 <- c(4.3, 8.9, 2.6, 7.1)
fox3 <- c(9.0, 12.5, 5.4, NA)
ringtail3 + fox3

# more
fox - ringtail
# scalar multiplier
100 * ringtail

#dot product ----
ringtail %*% fox
```

